INSERT INTO Certificateurs VALUES 
( '1','3W academy' ),
( '2','Aactes & formations' ),
( '3','Académie Charpentier' ),
( '4','Académie Internationale de Coupe de Paris' ),
( '5','ACF alternance - conseil - formation' ),
( '6','ACTEMOS' ),
( '7','Actions perspectives & compétences' ),
( '8','ADI' ),
( '9','ADIEL' ),
( '10','A fleur de peau' ),
( '11','AFNOR' ),
( '12','AFTRAL' ),
( '13','Agence européenne du management culturel (AEMC)' ),
( '14','AGR l''école de l''image' ),
( '15','Akor consulting' ),
( '16','Alenvi' ),
( '17','American university of Paris (AUP)' ),
( '18','AP Formation' ),
( '19','ARAFDES' ),
( '20','Arfis' ),
( '21','ARIES PACA' ),
( '22','ARIES Toulouse' ),
( '23','Artemisia formation' ),
( '24','ArtFx' ),
( '25','ASE formation' ),
( '26','Assemblée permanente des chambres de métiers et de l''artisanat (APCMA)' ),
( '27','Association des cours professionnels de pharmacie, santé, sanitaire, sociale et environnement' ),
( '28','Association française des fundraisers' ),
( '29','Association internationale pour la formation' ),
( '30','Association nationale de formation en gérontologie' ),
( '31','Association pour la Formation aux Techniques Industrielles (AFTI)' ),
( '32','Association pour la formation des ruraux aux activités du tourisme (AFRAT)' ),
( '33','Association pour la formation et l''enseignement en France de la chiropractique' ),
( '34','Association pour la progression des techniques internationales de management' ),
( '35','Association savoyarde pour le développement des énergies renouvelables (ASDER)' ),
( '36','Atelier Chardon Savard,L''institut supérieur des arts appliqués (LISAA) - Paris' ),
( '37','Atelier école déco' ),
( '38','Ateliers terre et feu - Paris' ),
( '39','Atorg' ),
( '40','Autograf' ),
( '41','AVEA Partners' ),
( '42','BGE Réseau' ),
( '43','Buroscope' ),
( '44','CCI de Paris Ile-de-France' ),
( '45','CCI France' ),
( '46','CDAF Formation,Eduservices' ),
( '47','Cegos' ),
( '48','centre d''études franco-américain de management' ),
( '49','Centre de formation des travaux publics (CFTP Emile Pico)' ),
( '50','Centre de formation professionnel de sécurité privée' ),
( '51','Centre de formation professionnelle aux techniques du spectacle (CFPTS)' ),
( '52','Centre de formation professionnelle des métiers du son (CFPMS)' ),
( '53','Centre de formation professionnelle et de promotion agricole (CFPPA) des Savoies et du Bugey' ),
( '54','Centre de recherches et d''études en formation et organisation (CREFO)' ),
( '56','Centre européen d''enseignement supérieur de l''ostéopathie' ),
( '57','centre international d''ostéopathie' ),
( '58','Centre national d''enseignement et de développement du secourisme' ),
( '59','Centre national de la prévention et de la protection (CNPP)' ),
( '60','Centre privé de formation professionnelle de l''union des usagers du port de Rouen' ),
( '61','Centre régional d''études supérieures pour la préparation aux affaires' ),
( '62','Centre régional de formation des professionnels de l''enfance' ),
( '63','Certidev' ),
( '64','CFA du pays de Montbéliard' ),
( '65','CGSAT' ),
( '66','CHAMBRE DE COMMERCE ET D''INDUSTRIE' ),
( '67','Chambre de Commerce et d''Industrie de région Paris Ile de France' ),
( '68','Chambre de Commerce et d''Industrie de région Paris Ile-de-France' ),
( '69','Chambre de Commerce et d''Industrie de région Paris Ile-de-France,Gobelins - Ecole de l''image' ),
( '70','Chambre Franco-Allemande de Commerce et d''Industrie' ),
( '71','Chambres de commerce et d''industrie (CCI)' ),
( '72','CIFACOM' ),
( '73','Cité de la musique' ),
( '74','Cod Formation SAS' ),
( '75','Collège de Paris' ),
( '76','Collège ostéopathique de Provence Aix-Marseille (COP Aix-Marseille)' ),
( '77','Collège ostéopathique Sutherland de Strasbourg' ),
( '78','Comité scientifique et technique des industries climatiques' ),
( '79','Comundi' ),
( '80','Confédération de l''artisanat et des petites entreprises du bâtiment (CAPEB)' ),
( '81','Conservatoire Européen d''Écriture Audiovisuelle (CEEA)' ),
( '82','Conservatoire supérieur ostéopathique - Toulouse' ),
( '83','Couleurs de forge' ),
( '84','Cours d''esthétique privé à option humanitaire et sociale (CODES)' ),
( '85','Cours Florent' ),
( '86','Cours hôtelier de Besançon' ),
( '87','CPNE de l''audiovisuel' ),
( '88','CPNE des bâtiment et travaux publics' ),
( '89','CPNE des commerces de gros' ),
( '90','CPNE des entreprises de prévention et sécurité' ),
( '91','CPNE des équipements thermiques' ),
( '92','CPNE des hôtels, cafés restaurants (HCR)' ),
( '93','CPNE des industrie et commerce de la récupération' ),
( '94','CPNE des sociétés d''assurances' ),
( '95','CPNE du personnel des entreprises de restauration de collectivités' ),
( '96','CPNE du spectacle vivant' ),
( '97','CQFD' ),
( '98','CREAD' ),
( '99','Créa image communication' ),
( '100','CTI (Centre de techniques internationales)' ),
( '101','Culture et formation' ),
( '102','DELTA sud formation' ),
( '103','Didascalis' ),
( '104','Direction générale de l''aviation civile' ),
( '105','Direction générale de la santé' ),
( '106','Doranco espace multimédia' ),
( '107','Dtalents' ),
( '108','e-artsup institut' ),
( '109','Easy Success' ),
( '110','Ecole bleue' ),
( '111','Ecole Brassart' ),
( '112','Ecole Camondo' ),
( '113','Ecole d''ingénieurs en génie des systèmes industriels (EIGSI)' ),
( '114','Ecole de bibliothécaires documentalistes (EBD)' ),
( '115','ECOLE DE CONDE' ),
( '116','Ecole de la performance' ),
( '117','Ecole de management Léonard de Vinci (EMLV)' ),
( '118','Ecole des métiers de l''information (CFD)' ),
( '119','École du journalisme' ),
( '120','Ecole Emile Cohl' ),
( '121','Ecole européenne de l''art et des matières' ),
( '122','Ecole européenne des métiers de l''internet (EEMI)' ),
( '123','École française de journalisme (EFJ)' ),
( '124','Ecole française du décor peint' ),
( '125','Ecole klaxon rouge' ),
( '126','Ecole pour l''informatique et les nouvelles technologies (EPITECH)' ),
( '127','Ecole pour l''informatique et les techniques avancées (EPITA)' ),
( '128','Ecole Richard Cross' ),
( '129','Ecole spéciale d''architecture (ESA)' ),
( '130','Ecole spéciale des travaux publics du bâtiment et de l''industrie (ESTP)' ),
( '131','Ecole supérieur des métiers du web' ),
( '132','École supérieure d''assurances' ),
( '133','Ecole supérieure d''ébénisterie d''Avignon (ESEA)' ),
( '134','Ecole supérieure d''études cinématographiques (ESEC)' ),
( '135','Ecole supérieure d''informatique électronique automatique (ESIEA)' ),
( '136','École supérieure d''informatique et de commerce' ),
( '137','Ecole supérieure d''ingénieurs en génie électrique (ESIGELEC)' ),
( '138','Ecole supérieure de commerce et d''administration des entreprises du tourisme (ESCAET)' ),
( '139','Ecole supérieure de communication Lille' ),
( '140','Ecole supérieure de journalisme de Paris (ESJ PARIS)' ),
( '141','Ecole supérieure de la création graphique' ),
( '142','Ecole supérieure de réalisation audiovisuelle (ESRA Bretagne)' ),
( '143','Ecole supérieure de réalisation audiovisuelle (ESRA Côte d''Azur)' ),
( '144','Ecole supérieure de réalisation audiovisuelle (ESRA Paris)' ),
( '145','Ecole supérieure des arts modernes - ESAM Design' ),
( '146','Ecole Supérieure des Jeunes Dirigeants du Bâtiment (ESJDB)' ),
( '147','Ecole supérieure des métiers de l''image' ),
( '148','École supérieure des métiers de l''image, du son et du multimédia (EMC)' ),
( '149','Ecole supérieure des Pays de Loire (ESPL)' ),
( '150','Ecole supérieure des professions immobilières (ESPI)' ),
( '151','Ecole supérieure des sciences économiques et commerciales (Groupe ESSEC)' ),
( '152','Ecole supérieure des transports' ),
( '153','Ecole supérieure génie informatique (ANAPIJ)' ),
( '154','Edinovo formation' ),
( '155','EDUCSUP' ),
( '156','Eduservices' ),
( '157','Eduservices,Institut des professions des affaires et du commerce d''Annecy (IPAC)' ),
( '158','Eduservices bordeaux' ),
( '159','EFGC' ),
( '160','EMD école de management' ),
( '161','ENI - Ecole informatique' ),
( '162','ENSA - 2i - INSTA' ),
( '163','Enseignement-formation-insertion-promotion' ),
( '164','Enseignement supérieur d''ingénierie appliquée à la thermique, l''énergie et l''environnement (ENSIATE)' ),
( '165','Epsilon à l''Ecole' ),
( '166','ESC Force Ouest-Brest Business School' ),
( '167','ESIMODE - école mode Toulouse' ),
( '168','ESMOD' ),
( '169','Espace Sentein' ),
( '170','ESTRI - Ecole supérieure de traduction et relations internationales (ESTRI)  / Facultés catholiques de Lyon' ),
( '171','e-tribArt Institut' ),
( '172','ETS Global' ),
( '173','Etudes supérieures appliquées aux affaires (ESA3)' ),
( '174','Euridis Management' ),
( '175','European school of advanced management - Groupe institut de gestion sociale (IGS)' ),
( '176','Excellens formation' ),
( '177','Fédération française d''équitation' ),
( '178','Fédération française de football (FFF)' ),
( '179','Fédération française de golf' ),
( '180','Fédération française des associations de chiens guides d''aveugles (FFAC)' ),
( '181','Fédération Française des techniciens dentaires équins' ),
( '182','Fédération nationale de sapeurs-pompiers de France' ),
( '183','Fédération nationale des associations d''accueil et de réinsertion sociale (FNARS)' ),
( '184','Formamod' ),
( '185','Formation conseil Thalatherm' ),
( '186','Formation pour la restauration du patrimoine en Berry (FOREPABE)' ),
( '187','GCAF Sup''tertiaire' ),
( '188','GEM Formation Conseil' ),
( '189','Gobelins - Ecole de l''image' ),
( '190','Gofluent' ),
( '191','GRETA du Gard' ),
( '192','Groupe 4' ),
( '193','GROUPE 9 ACADEMY' ),
( '194','Groupe institut de gestion sociale (IGS)' ),
( '195','Groupement d''enseignement supérieur commercial de l''Est parisien' ),
( '196','Groupement d''intérêt public (GIP) Formavie Montpellier' ),
( '197','Groupement d''intérêt public formation continue et insertion professionnelle (GIP FCIP) - Alsace' ),
( '198','Groupement d''intérêt public formation continue et insertion professionnelle (GIP FCIP) - Créteil' ),
( '199','Groupement d''intérêt public formation continue et insertion professionnelle (GIP FCIP) - Toulouse' ),
( '200','Groupement d''intérêt public formation et insertion professionnelle (GIP FCIP) - Franche-Comté' ),
( '201','Groupe Sciences U' ),
( '202','Groupe Silvya Terrade' ),
( '203','HITEMA' ),
( '204','IBSM Mode et Marketing' ),
( '205','Inéa Conseil' ),
( '206','Ink Company - École française de tatouage' ),
( '207','institut bioforce développement' ),
( '208','Institut catholique de Lille' ),
( '209','Institut catholique de Paris' ),
( '210','Institut commercial lyonnais (ICL)' ),
( '211','Institut d''études des relations internationales (ILERI-ILECI)' ),
( '212','Institut de conciergerie internationale' ),
( '213','Institut de développement et d''enseignement méditerranéen (IDEM)' ),
( '214','Institut de formation au management de transition' ),
( '215','Institut de formation de la profession de l''assurance' ),
( '216','Institut de formation du bâtiment et des travaux publics Rhône-Alpes (IFBTP RA)' ),
( '217','Institut de formation du crédit agricole mutuel' ),
( '218','Institut de formation en commerce et oenologie' ),
( '219','Institut de formation et d''appui aux initiatives de développement (IFAID)' ),
( '220','Institut de formation et de recherche du batiment' ),
( '221','Institut de formation industrie de santé (IFIS)' ),
( '222','Institut de formation industrielle (IFI)' ),
( '223','Institut de formation régional des industries alimentaires de Bretagne (IFRIA)' ),
( '224','Institut de formations supérieures du Grand Ouest' ),
( '225','Institut de gestion et d''études financières (IGEFI)' ),
( '226','Institut de management commercial (IMC)' ),
( '227','Institut de management des industries de la santé (IMIS)' ),
( '228','Institut de management des services immobiliers' ),
( '229','Institut de promotion et de formation' ),
( '230','Institut de recherche et d''action commerciale (IDRAC)' ),
( '231','Institut de Recherche et de Formation en Art-Thérapie (IRFAT)' ),
( '232','Institut de recherche pédagogique audiovisuel' ),
( '233','Institut de relooking international' ),
( '234','Institut des hautes études de droit rural et d''économie agricole' ),
( '235','Institut des métiers de la communication audiovisuelle de Provence' ),
( '236','Institut des professions des affaires et du commerce d''Annecy (IPAC)' ),
( '237','Institut des sciences de la vision (ISV)' ),
( '238','Institut européen de formation aux mécaniques sportives' ),
( '239','Institut français de gestion (IFG)' ),
( '240','Institut français de gestion (IFG),MBA Institute - INSEEC' ),
( '241','Institut français de la médiation' ),
( '242','Institut français de la mode' ),
( '243','Institut français de sécurité' ),
( '244','Institut Français de Zoothérapie' ),
( '245','Institut international de communication de Paris (IICP)' ),
( '246','Institut juridique d''Aquitaine (IJA)' ),
( '247','Institut national d''expression, de création, d''art et transformation' ),
( '248','Institut national de l''audiovisuel (INA)' ),
( '249','Institut national des hautes études de la sécurité et de la justice' ),
( '250','Institut pour la promotion de l''enseignement et du conseil' ),
( '251','Institut régional universitaire polytechnique (IRUP)' ),
( '252','Institut rural de Carquefou' ),
( '253','Institut SESAM' ),
( '254','Institut supérieur d''agriculture et d''agroalimentaire Rhône-Alpes (ISARA Lyon)' ),
( '255','Institut supérieur de communication et publicité (ISCOM)' ),
( '256','Institut supérieur de formation au journalisme (ISFJ)' ),
( '257','Institut supérieur de l''environnement (ISE)' ),
( '258','institut supérieur des carrières artistiques' ),
( '259','Institut supérieur des techniques du spectacle (ISTS)' ),
( '260','Institut supérieur des technologies de la formation' ),
( '261','Institut supérieur de technologie de Lyon (Sup'' La Mache)' ),
( '262','Institut supérieur du management public et politique' ),
( '263','Institut supérieur du vin' ),
( '264','Institut supérieur européen de gestion (ISEG)' ),
( '265','INSTITUT SUPERIEUR EUROPEEN DE LA MODE - ISEM' ),
( '266','Institut supérieur Maria Montessori' ),
( '267','Institut technologique européen des métiers de la musique' ),
( '268','Institut textile et chimique de Lyon' ),
( '269','Institut toulousain d''ostéopathie' ),
( '270','Institut Vatel' ),
( '271','IONIS School of technology and management Paris' ),
( '272','Ironhack' ),
( '273','ISART Digital - Institut supérieur de l''art digital' ),
( '274','Istituto Marangoni France SAS' ),
( '275','ISVM' ),
( '276','ITECOM Art design - Paris' ),
( '277','Juriscampus' ),
( '278','L''Aronde des oliviers - Ecole supérieure d''ébénisterie de Haute-Provence' ),
( '279','L''École Multimédia' ),
( '280','L''institut supérieur des arts appliqués (LISAA) - Paris' ),
( '281','La Poudrière - Ecole du film d''animation' ),
( '282','Le Samovar' ),
( '283','Les formations d''Issoudun' ),
( '284','Lingueo' ),
( '285','MBA Institute - INSEEC' ),
( '286','Ministère de l''agriculture, de la souveraineté alimentaire et de la forêt' ),
( '287','Ministère de l''agriculture et de la pêche' ),
( '288','Ministère de l''économie' ),
( '289','Ministère de l''économie, des finances et de l''industrie' ),
( '290','Ministère de l''éducation nationale' ),
( '291','Ministère de l''éducation nationale, de la jeunesse et de la vie associative' ),
( '294','Ministère de l''Enseignement supérieur, de la Recherche et de l''Innovation' ),
( '295','Ministère de l''Enseignement supérieur et de la Recherche' ),
( '296','Ministère de l''Enseignement supérieur et de la Recherche,Ministère de la santé et de l''accès aux soins' ),
( '297','Ministère de l''intérieur, de l''Outre-Mer, des collectivités territoriales et de l''immigration' ),
( '300','Ministère de l''intérieur et des outre-mer' ),
( '301','Ministère de la culture' ),
( '302','Ministère de la culture et de la communication' ),
( '303','Ministère de la justice' ),
( '304','Ministère de la santé, jeunesse et sports' ),
( '305','Ministère de la santé et de l''accès aux soins' ),
( '306','Ministère de la transition écologique, de l''énergie, du climat et de la prévention des risques' ),
( '307','Ministère des affaires sociales et de la santé' ),
( '308','Ministère des armées et des anciens combattants' ),
( '309','Ministère des sports, de la jeunesse et de la vie associative' ),
( '310','Ministère du travail et de l''emploi' ),
( '311','MJM Graphic Design (MJM) - Paris' ),
( '312','Mod''art International - SIGE' ),
( '313','Nouvel R formation' ),
( '314','OCTO Technology' ),
( '315','OpenClassrooms' ),
( '316','Philharmonie de Paris' ),
( '317','Pôle formation santé' ),
( '318','Promotrans' ),
( '319','Régie autonome des transports parisiens (RATP)' ),
( '320','Réseau Ducretet' ),
( '321','ROYER ROBIN Associés' ),
( '322','SAS Soprema - centre de formation' ),
( '323','Scalisi Christian' ),
( '324','Secrétariat d''Etat aux transports' ),
( '325','Secrétariat général de l''enseignement catholique' ),
( '326','Service médical de la présidence de la République' ),
( '327','Societe de gestion, de formation et de conseil' ),
( '328','Société française d''étude et de formation (SFEF)' ),
( '329','Société nationale des chemins de fer français' ),
( '330','Spectacle et techniques - Association française de formation' ),
( '331','Speos Paris photographic institute' ),
( '332','Sup''CG Management & Networks' ),
( '333','SUPCREA Grenoble' ),
( '334','Sup de pub - groupe INSEEC' ),
( '335','Syndicat des entreprises de déconstruction, dépollution et de recyclage' ),
( '336','Syndicat national de l''orthopédie française (SNOF)' ),
( '337','Union des centres de plein air (UCPA)' ),
( '338','Union des industries et métiers de la métallurgie (UIMM)' ),
( '339','Union intersecteurs papiers cartons pour le dialogue et l''ingénierie sociale' ),
( '340','Union nationale des maisons familiales rurales d''éducation et d''orientation (UNMFREO)' ),
( '341','Union professionnelle des métiers de la finition de la fédération française du bâtiment' ),
( '342','Union professionnelle des professeurs, cadres et techniciens du secrétariat et de la comptabilité' ),
( '343','Université du vin' ),
( '344','Variations international' ),
( '345','VISIPLUS academy' ),
( '346','Visuel - Langue des Signes Française' ),
( '347','Webmarketing & co''m' ),
( '348','YNOV');
